INSERT INTO abbreviations(value) VALUES
('abbr'),
('afaik'),
('ama'),
('atea'),
('cmv'),
('dae'),
('diy'),
('eli5'),
('ftfy'),
('iama'),
('ianad'),
('ianal'),
('iirc'),
('imo'),
('imho'),
('itt'),
('misc'),
('mrw'),
('mfw'),
('nsfl'),
('nsfw'),
('op'),
('psa'),
('til'),
('tldr'),
('ysk');

INSERT INTO expansions(value) VALUES
('abbreviation'),
('as far as i know'),
('ask me anything'),
('abbreviated text expansion algorithm'),
('change my view'),
('does anyone else'),
('do it yourself'),
("explain like i'm five"),
('fixed that for you'),
('i am a'),
('i am not a doctor'),
('i am not a lawyer'),
('if i recall correctly'),
('in my opinion'),
('in my humble opinion'),
('in this thread'),
('miscellaneous'),
('my reaction when'),
('my face when'),
('not safe for life'),
('not safe for work'),
('original poster'),
('public service announcement'),
('today i learned'),
("too long didn't read"),
('you should know');

INSERT INTO abbreviation_expansion VALUES (1,1),(2,2),(3,3),(4,4),(5,5),(6,6),(7,7),(8,8),(9,9),(10,10),(11,11),(12,12),(13,13),(14,14),(15,15),(16,16),(17,17),(18,18),(19,19),(20,20),(21,21),(22,22),(23,23),(24,24),(25,25);

INSERT INTO examples VALUES
(1, 1, 1, ',An,abbr,is,a,shortened,form,of,a,word,DIY,and,misc,are,examples,of,abbreviations,', 1),
(2, 7, 7, ',An,abbr,is,a,shortened,form,of,a,word,DIY,and,misc,are,examples,of,abbreviations,', 9),
(3, 17, 17, ',An,abbr,is,a,shortened,form,of,a,word,DIY,and,misc,are,examples,of,abbreviations,', 11);
